version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

sphinx:
  configuration: doc/source/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
